language: node_js
node_js:
- 12.14.1
install: npm install
script: npm run test
deploy:
  provider: heroku
  api_key:
    secure: "HGXWkNJ5obpuz8plPghzQuF15TR6IybjCITVLRXqD2QQOtxlIjJNZ+3e77sk9YDZTJSH6/BnNwvETVm5ahHGoEmKepy1K2/OewpfA1qAIWTconovg78z3R4UQi0euij5hivhz0Hkl7lwfPReZMk2qkViQetSjp6icQnQYwc2Sicko7uVBUQwVISmVs5v6MWKaRXyc6qYsKDtrhX9oV3Lly6UxrYaKnNn5UdLCmB4UmvIRun8BqB41vKnz1RVeKmOr/Pyd+v2oUh2yDenDKV80+u9k4MZ/bUTDblknbFvw9ae3OiuLQZbV9OBh5zrRwrcqtmsI986aHGej5LrqMESZBcegCgm/GqXCprQB+3No9ZlKhUnKbOS5CVye00oOMPZwjSj/6Gn+1md8XSGGQM4SqVSOH/JTyh/l46twXloB13NYxptXc4e/i78/0KDRAELcJiw0TV3QYZ7v7F+BOCACHE55Ilq0dUP/RQg7oovD7QytdEk7fw4Md5O6fHBbHLQY7XBlzS1srviQlZMsbYIU0jwmsbXI/Kl/xd0RfhWU2Hutzpnemq1OnlZHD9rjjK9qUIWIwPJRFgQM1YSiSeijA9NEdrYxSwNtmZApwuQXIhpL5a8AWijBTytjRP3vzRMbJwIHDBFRrM57daK1UBI3CDaIwKV23vNOvgdH6ITwJ4="
  app: make-up-products

